"""Add user_type column

Revision ID: 216ba5ece5a2
Revises: db1cdb1d59c7
Create Date: 2025-07-25 15:59:34.376142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216ba5ece5a2'
down_revision: Union[str, Sequence[str], None] = 'db1cdb1d59c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
