"""add image column to products

Revision ID: a472503559bc
Revises: c0c2e0a86605
Create Date: 2025-08-11 17:45:47.257573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a472503559bc'
down_revision: Union[str, Sequence[str], None] = 'c0c2e0a86605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.VARCHAR(), nullable=True))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
