"""add image_path to products

Revision ID: c833a28a3023
Revises: 216ba5ece5a2
Create Date: 2025-08-11 16:53:57.072629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c833a28a3023'
down_revision: Union[str, Sequence[str], None] = '216ba5ece5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
